# Generated by Django 4.0.6 on 2022-07-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscrire', '0008_alter_etudiant_prive_master_niveau1_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commantire', models.CharField(max_length=500)),
                ('fichiere', models.Field(null=True)),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
