# Generated by Django 4.0.6 on 2022-07-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscrire', '0009_arrchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrchive',
            name='fichiere',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
