# Generated by Django 4.0.6 on 2022-07-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inscrire', '0010_alter_arrchive_fichiere'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arrchive',
        ),
    ]
