# Generated by Django 4.0.6 on 2022-07-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inscrire', '0012_arrchive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrchive',
            name='fichiere',
        ),
    ]
