# Generated by Django 4.0.6 on 2022-07-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscrire', '0013_remove_arrchive_fichiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrchive',
            name='fich',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
