# Generated by Django 4.0.6 on 2022-07-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inscrire', '0014_arrchive_fich'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arrchive',
        ),
    ]
